[colors.bright]
black = "#777777"
blue = "#87afdf"
cyan = "#a0eeff"
green = "#bdff9d"
magenta = "#b0a0ff"
red = "#df8787"
white = "#fcfcfc"
yellow = "#ffe0a0"

[colors.cursor]
cursor = "#006400"
text = "#000000"

[colors.normal]
black = "#2a2a2a"
blue = "#87afd7"
cyan = "#78e7ff"
green = "#b6ff93"
magenta = "#8f78ff"
red = "#d78787"
white = "#cccbca"
yellow = "#ffd378"

[colors.primary]
background = "#1c1c1c"
foreground = "#d0d0d0"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "DejaVuSansM Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
