[tool.poetry]
name = "sway-scripts"
version = "0.1.0"
description = ""
authors = ["Maxim Andreev <andreevmaxim@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
i3ipc = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
